"""empty message

Revision ID: 33b112d653fa
Revises: bcf65a81cff3
Create Date: 2022-06-24 01:02:33.841989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b112d653fa'
down_revision = 'bcf65a81cff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_at_timestamp', sa.Integer(), nullable=True))
    op.drop_column('books', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_at', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('books', 'created_at_timestamp')
    # ### end Alembic commands ###
